version: "3.9"

services:
  db:
    image: postgres:15
    container_name: vehiculos_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p.7891011
      POSTGRES_DB: VehiculosDB
      TZ: "America/Guayaquil"  # <-- Zona horaria correcta
    volumes:
      - vehiculos_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro  # <-- sincroniza hora con host
      - /etc/timezone:/etc/timezone:ro    # <-- sincroniza zona horaria
    networks:
      - app_net
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: placas_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_net

volumes:
  vehiculos_data:

networks:
  app_net:
    driver: bridge
